# server:
#   persistentVolume:
#     enabled: false
alertmanager:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
    hostDomain: supaman.home
    hosts:
      - alertmanager.supaman.home
    paths:
      - /
  service:
    type: NodePort

grafana:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
    hostDomain: supaman.home
    hosts:
      - grafana.supaman.home
    paths:
      - /
  service:
    type: NodePort

prometheus:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
    hostDomain: supaman.home
    hosts:
      - prometheus.supaman.home
    paths:
      - /
  service:
    type: NodePort


