# server:
#   persistentVolume:
#     enabled: false

alertmanager:
  ingress:
    enabled: true
    ingressClassName: cloudflare-tunnel
    hostDomain: supaperman.net
    hosts:
      - alertmanager.supaperman.net
    paths:
      - /
    pathType: Prefix
  service:
    type: ClusterIP

grafana:
  ingress:
    enabled: true
    ingressClassName: cloudflare-tunnel
    hostDomain: supaperman.net
    hosts:
      - grafana.supaperman.net
    paths:
      - /
    pathType: Prefix

  service:
    type: ClusterIP

  grafana.ini:
    server:
      root_url: https://grafana.supaperman.net
    auth.generic_oauth:
      enabled: true
      name: Keyclaok-OAuth
      allow_sign_up: true
      client_id: https://grafana.supaperman.net
      scopes: openid email profile offline_access roles
      email_attribute_path: email
      login_attribute_path: username
      name_attribute_path: full_name
      auth_url: https://keycloak.supaperman.net/realms/ktp/protocol/openid-connect/auth
      token_url: https://keycloak.supaperman.net/realms/ktp/protocol/openid-connect/token
      api_url: https://keycloak.supaperman.net/realms/ktp/protocol/openid-connect/userinfo
      role_attribute_path: contains(realm_access.roles[], 'grafana_admin') && 'Admin' || contains(realm_access.roles[], 'grafana_editor') && 'Editor' || 'Viewer'
    users:
      auto_assign_org: true
      auto_assign_org_role: Editor

prometheus:
  ingress:
    enabled: true
    ingressClassName: cloudflare-tunnel
    hostDomain: supaperman.net
    hosts:
      - prometheus.supaperman.net
    paths:
      - /
    pathType: Prefix
  service:
    type: ClusterIP
