apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vaultwarden.fullname" . }}
  annotations:
    kubernetes.io/service-account.name: {{ include "vaultwarden.serviceAccountName" . }}
type: Opaque
data:
  {{- range $key, $value := .Values.envSecret }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
