repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

releases:
  - name: kube-prometheus-stack
    namespace: prometheus
    chart: prometheus-community/kube-prometheus-stack
    version: 61.2.0
    values:
      - values/kube-prometheus-stack.yaml
    secrets:
      - secrets/kube-prometheus-stack.yaml
