apiVersion: v1
kind: Secret
metadata:
  name: postgre-secret
  namespace: misskey
data:
  POSTGRES_PASSWORD: cGFzc3dvcmQ=
type: Opaque
stringData:
  POSTGRES_USER: misskey
  POSTGRES_DB: misskey

---

apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: misskey
spec:
  selector:
    app: db
  ports:
  - name: http
    port: 5432

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-misskey-db
  namespace: misskey
spec:
  storageClassName: nfs-client
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi

---

apiVersion: v1
kind: Pod
metadata:
  name: db
  namespace: misskey
  labels:
    app: db
spec:
  # affinity:
  #   nodeAffinity:
  #     requiredDuringSchedulingIgnoredDuringExecution:
  #       nodeSelectorTerms:
  #       - matchExpressions:
  #         - key: kubernetes.io/hostname
  #           operator: In
  #           values:
  #             - pi41
  restartPolicy: Always
  containers:
  - name: psql
    image: postgres:16
    # command: ["/bin/sh", "-c"]
    # args: ["exec gosu postgres postgres -c /var/lib/postgresql/data/postgresql.conf"]
    volumeMounts:
    - mountPath: /var/lib/postgresql/data
      name: db-volume
    envFrom:
      - secretRef:
          name: postgre-secret
    resources:
      limits:
        memory: "800Mi"
        cpu: "1"
    ports:
    - containerPort: 5432
  volumes:
  - name: db-volume
    persistentVolumeClaim:
      claimName: pvc-misskey-db
