spec:
    addresses:
        - ENC[AES256_GCM,data:LYVQdw7pd6/cxFNYr6IpSlwh3sFq2qJYErPhjw==,iv:iL9F/kMmfgQEsi11AnPMKvwQAHoc5PmJfWQr0RvVDjs=,tag:dIbrdktk1B7RXZogphSSOA==,type:str]
        - ENC[AES256_GCM,data:h2mbMU0ADextMttdbiRvPAvB+qxXFuvGqPsVr2k=,iv:OBmdh/+oet9rg7u3Gu73K/xhadlXiVYZR24DTmf7NL4=,tag:rZU7hQ5/YwecXNVPZhrchA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wqgppd3k2tcv266wr07vrn0fn78eqmj8duly3wslnqfxu5dakals79rfej
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJQkRmVVZCY1l4dWVXbC9M
            NkkrZVRUZUJBY04wY1JUZEhJZ2dPNUJOOEdVCjE3M2Y2YUhBWWFEQzBaZmdNdVBK
            SjV1ZEhPWUJFRm5VKzIxRE5WMTY5OTQKLS0tIFNxZXd3VldiMmdaZ0dubU9TV21K
            cHg1eUlEcllnOEJNeWhsRjZqWDJRVWsKIC/ZSWed98NSNUUeXFazWnBUfFEsu4Hs
            8yG6v14kVaIFrdFRXVOaoS4BFSnlZyELsIEuof2KmJwVIg6H7a3Qhg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-20T12:27:39Z"
    mac: ENC[AES256_GCM,data:Goe3oNkNwn1iKuE5huYdPVMcMXAcpZq3CR3LVmJYJnMGuxXD99wr+DbCFzw4TmL+1Tmuz7pnGp+n2i5JS3C040o/LRwCVU+KY4isHSI1IjRRSyKY/S8ndaSgfk/0dg+JPuHsJYp5bRtWcY2tV/S6Sbn9KGErKv/b1nCo2bZX68c=,iv:PwnqN2CFBGr5DwRVyqI+5R/+88r3Km/JHQxbZVZoiOA=,tag:d293Pzq/eEfUQAcwckAZvw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
